### ISSUE TITLE
[Feature Request] Add Support For Downloading Playlist

### ISSUE THREAD

**Issue by Spectrum75** [kanehekili/YoutubeDownloader#2]
Hello,
I just loved this youtube downloader and found it very useful. I just wanted to ask if it is possible to add support for downloading playlist too? Since youtube-dl is used (which can download playlists).

Thanks :blush:

**Comment by kanehekili** [comment]
Yes, my kids already asked me about it. I'll look into it

**Comment by Spectrum75** [comment]
Great, keep going :blush: :+1:

**Comment by kanehekili** [comment]
Updated to V1.30, supporting playlists.

**Comment by Spectrum75** [comment]
Awesome!
