### ISSUE TITLE
Icons don't have a good contrast with Dark themes

### ISSUE THREAD

**Issue by Aditya-Tolikar** [kanehekili/YoutubeDownloader#4]
Tried themes: Adwaita Dark, Breathe Dark, Breeze (Custom colours), Dark-openSUSE-GTK.
OS: Manjaro KDE 21.2.2
Problem: Icon colours are black even on Dark themes, making them difficult to see.

Possible Solution: Hopefully, should fix itself on replacing declarations similar to this:
`opentb = Gtk.ToolButton(stock_id=Gtk.STOCK_OPEN)`
...with the kind illustrated in [https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative](https://stackoverflow.com/questions/36805505/gtk-stock-is-deprecated-whats-the-alternative).

P.S.: Sorry, for the non-standard issue, I'm new to this.
I would have liked to help by sending a pull request. But since I haven't set up a Python GTK IDE to test it out..

**Comment by kanehekili** [comment]
Hi, Im using a dark theme on Manjaro, the icons look like this:
![image](https://user-images.githubusercontent.com/4390452/151235188-a977281f-b4b6-43a5-b8bb-e8e3eb801184.png)
Or are you talking about the "menu" items? (Which are red)

**Comment by kanehekili** [comment]
I'll look into the problem, since I'm using XFCE and not KDE. Icons should be clearly seen, so thanks for reporting.

**Comment by kanehekili** [comment]
Should be fixed with AUR Version 1.4.1.  Ubuntu will follow

**Comment by Aditya-Tolikar** [comment]
Thanks for the speedy reply.

Here's how it looks in Manjaro KDE
![Screenshot_20220127_065605](https://user-images.githubusercontent.com/13906260/151275920-6b7a0662-d4d7-4820-b306-d255b4c80bbc.png)
![breeze_customcolours_preview](https://user-images.githubusercontent.com/13906260/151275959-de03fb8a-3813-474b-82ea-540a2daaffc1.png)

Now that I think again, it might be a problem with the stock GTK icons that
are saved in my installation. I will see if that can be changed.

Regards,
Aditya Tolikar

**Comment by kanehekili** [comment]
Check the new version and report ... works with my dark GTK theme on KDE (https://www.pling.com/p/1424967/)

**Comment by Aditya-Tolikar** [comment]
Thanks, I checked out the new version. (Restarted too, just in case) And it
seems like my suggestion didn't work.
The icons seem to not have changed. I will check again after ~12 hours and
see if the default icon set on the installation is the reason.

**Comment by kanehekili** [comment]
Tested it with Breeze and Oxygen, you might have to change your GTK Settings. Which icon theme have you selected? You should select a "dark" icon theme

**Comment by Aditya-Tolikar** [comment]
> Tested it with Breeze and Oxygen, you might have to change your GTK Settings. Which icon theme have you selected? You should select a "dark" icon theme

It worked. Turned out I was using "Breeze" icon theme and needed to shift to Breeze Dark. I hadn't realized since KDE apps seem to change icon colours depending upon the theme (if the icon theme is Breeze), even if we don't change to a dark icon theme. But GTK apps don't do so when this is done with KDE's settings.
Thanks for the help even though it turned out to not be an issue with YoutubeDownloader.

**Comment by kanehekili** [comment]
No problem, since my way of using icons was deprecated. Thanks for pointing me to this.
