### ISSUE TITLE
ERROR: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by sl5net** [kanehekili/YoutubeDownloader#6]
```sh
youtube-dl -ix 'https://www.youtube.com/watch?v=5ev2XuSNvB0'
[youtube] 5ev2XuSNvB0: Downloading webpage
ERROR: 5ev2XuSNvB0: YouTube said: Unable to extract video data
```
what could i do ? thanks

**Comment by kanehekili** [comment]
Yep- thats the reason why this software uses yt-dlp. I am not the creator of youtube-dl, nor am I using it. 
Drag the link onto the list of this software and it will download it...
So I'm closing this
