### ISSUE TITLE
gui does not launch on Ubuntu 24.04

### ISSUE THREAD

**Issue by eric-w-hart** [kanehekili/YoutubeDownloader#7]
When trying to launch from the icon, nothing happens.
Launching from terminal with the command ytgui comes back with this error:

Traceback (most recent call last):
  File "/usr/bin/ytgui", line 7, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by kanehekili** [comment]
python3-gi is a prerequisite of YT. Have you changed the python environment?
What is the output of `which -a python3`?

You might execute
`sudo apt install python3-gi`
but the deb file should've installed that library.

**Comment by kanehekili** [comment]
Tested it on Jammy and noble. Noble has python3.12 installed and the install works without problems.  If another python version is installed you need to install the dependencies yourself - documented [here](https://github.com/kanehekili/YoutubeDownloader) for manual install
